run_name: "default"

num_epochs: 300
batch_size: 64
samples_per_lif: 4096
min_context_points: 16

lr_schedule:
  - { "Type" : "Step", "Initial" : 0.001, "Interval" : 80, "Factor" : 0.4 }

# Dataset.
train_set:
  - { "data_path": "../di-datasets/shapenet_plivoxs", "augment_rotation": 'Y', "num_surface_sample": 128, "augment_noise": [0.025, 40.0] }

# Code specification
code_bound: null
code_length: 29

# Snapshots saving parameters
snapshot_frequency: 100
additional_snapshots: []

# SDF samples
training_loss:
    types: [ "neg_log_likelihood", "reg_loss" ]
    enforce_minmax: true
    clamping_distance: 0.2
    code_reg_lambda: 1.0e-2
